#!/bin/bash

_set_bot () {
   # local zippath
    zippath="catuserbot.zip"
    echo "  Downloading source code ..."
   # wget -q https://ankitkumarbh:250298gh@github.com/ankitkumarbh/Tele-Bot/archive/master.zip -O "$zippath"
    git clone https://ankitkumarbh:250298gh@github.com/ankitkumarbh/Telegram-Userbot telebot
    echo "  Unpacking Data ..."
   # CATPATH=$(zipinfo -1 "$zippath" | grep -v "/.");
   # unzip -qq "$zippath"
    echo "Done"
    echo "  Cleaning ..."
   # rm -rf "$zippath"
   # cd $CATPATH
    cd telebot
    mkdir bin
    chmod -R 755 bin
    echo "    Starting UserBot    "
   # python3 ../setup/updater.py ../requirements.txt requirements.txt
    python3 -m telebot
}

_set_bot
